spring:
  data:
    mongodb:
      uri: mongodb://group7:secrets123@docdb-group7.cluster-c4eqo06kg56i.us-east-1.docdb.amazonaws.com:27017/?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      database: Tax-Application
  # enabling colors in the terminal
  output:
    ansi:
      enabled: ALWAYS
javax:
  net:
    ssl:
      trustStore: /tmp/certs/rds-truststore.jks
      trustStorePassword: secrets123

logging:
  level:
    com:
      skillstorm: debug
